In [37]:
## heart disease prediction using logistic regression

In [38]:
import numpy as np 
import pandas as pd

In [39]:
df=pd.read_csv("heart-disease.csv")

In [40]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [41]:
df.shape

(303, 14)

In [42]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [44]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [45]:
df.isnull()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,False,False,False,False,False,False,False,False,False,False,False,False,False,False
299,False,False,False,False,False,False,False,False,False,False,False,False,False,False
300,False,False,False,False,False,False,False,False,False,False,False,False,False,False
301,False,False,False,False,False,False,False,False,False,False,False,False,False,False
302,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [46]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [47]:
df.duplicated().sum()

np.int64(1)

In [48]:
df=df.drop_duplicates()

In [49]:
df.shape

(302, 14)

In [50]:
df["target"].value_counts()

target
1    164
0    138
Name: count, dtype: int64

In [51]:
y=df["target"]
x=df.drop("target",axis=1)

In [52]:
x.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [53]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [54]:
from sklearn.model_selection import train_test_split

In [55]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42
)

In [56]:
X_train.shape

(241, 13)

In [57]:
X_test.shape

(61, 13)

In [58]:
from sklearn.preprocessing import StandardScaler

In [59]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [60]:
print(X_train[:5])

[[-1.350641    0.73145871  0.         -0.63071093  0.92713761 -0.39129279
   0.89002765  0.54913872 -0.6591842  -0.89583663  0.96543644 -0.68348955
  -0.54576155]
 [ 1.48742624  0.73145871  0.9664929   2.75336332  0.5269804   2.55563104
  -0.99152203  0.01207102  1.51702665  0.54347422 -0.68470669 -0.68348955
   1.14050171]
 [ 1.37826981  0.73145871 -0.9664929  -0.34870475  0.1458783   2.55563104
   0.89002765  0.59389436 -0.6591842  -0.71592277 -0.68470669  1.35010281
   1.14050171]
 [ 0.06839262 -1.36713116  0.          0.21530763  0.06965787 -0.39129279
  -0.99152203  0.50438308 -0.6591842   0.36356037 -0.68470669 -0.68348955
  -0.54576155]
 [ 1.05080051  0.73145871  0.9664929   0.49731382  1.68934182 -0.39129279
   0.89002765  0.37011616 -0.6591842  -0.89583663  0.96543644 -0.68348955
  -0.54576155]]

In [61]:
from sklearn.linear_model import LogisticRegression

In [62]:
model=LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [63]:
y_pred=model.predict(X_test)

In [64]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy=accuracy_score(y_test,y_pred)
print("accuracy : ",accuracy*100)

accuracy :  86.88524590163934

: